### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by unitof** [initialcommit-com/git-sim#103]
Hi!

`git-sim`'s [LICENSE file](https://github.com/initialcommit-com/git-sim/blob/32a3a3fca583f6c68225b974716e74b557a1a094/LICENSE) is GNU 2.0, but its PyPI package is [marked MIT License](https://github.com/initialcommit-com/git-sim/blob/32a3a3fca583f6c68225b974716e74b557a1a094/pyproject.toml#L30).

Just curious if you could clarify what the license is, or if it's both. Thanks!

**Comment by initialcommit-io** [comment]
Hi @unitof ,

Thanks for asking - it's GNU GPL v2.0.  I must have missed the default license specified in the pyproject.toml file - I will update that shortly, thank you for bringing the discrepancy to my attention 😄.

For reference, the reason I chose GNU 2.0 when releasing Git-Sim was to align with the Git core license in case of a potential collaboration there.  No such collaboration has materialized, so if there was a reason to switch to MIT I would be open to considering it.

Just out of curiosity, are you planning to leverage Git-Sim in a project?  Because that would be very cool.  I'm actually hooking into it in another project I'm currently working on, so I will be releasing some enhancements and bugfixes to Git-Sim as a part of that in the near future.

**Comment by unitof** [comment]
Thanks!

I'm tinkering with making a `git-sim` Homebrew formula, actually: https://github.com/Homebrew/homebrew-core/pull/166775

I never got the knack of python venvs and pip installs CLI tools to places that still [scare me and break other stuff](https://xkcd.com/1987/), so when I find a python CLI tool that's just plain useful, packaging it into a Homebrew formula has become a bit of a hobby. (And, highly recommended full-immersion learning deep dive into build systems and scripting.)

I think I discovered git-sim via pinboard.in last year, and instantly tried to add it to Homebrew, to discover that manim hadn't been added! _That_ led me on a journey that's hopefully soon to pay off: https://github.com/Homebrew/homebrew-core/pull/166434

**Comment by initialcommit-io** [comment]
Oh nice!! That's really cool, and I appreciate you doing it😄.

If it gets accepted and works I'll update the Git-Sim docs for MacOS users to have a more convenient way to install it.

Thinking back, I probably should have put more work into making Git-Sim a dedicated installer instead of making users install via Pip, especially since the install base has grown.

But I don't have much experience creating installers and the dependence on Manim + it's own dependencies (mainly ffmpeg I think) made things a bit ... uncertain.  I wasn't sure how to bundle it all together at the time.

Any chance you have experience with that sort of thing?  Maybe it's easier than I realize...

**Comment by unitof** [comment]
Yeah. I'm finding there's been a bit of drama in recent years among the Homebrew maintainers involving Python & Python applications/libraries (I'm finding the border is fuzzy).

I am not a Python developer but it seems to me it was simultaneously ahead of the curve in creating a One True Package Index, but failed to account for dependency resolution locally to each project, leading to virtual environment madness for those of us who just want some convenience CLI tools.

I think Homebrew, strict as they are, are on the right side of resolving this: just support the latest version of everything, but build bottles for each platform.

Anyway, as you point out, if accepted I think this works really well to ensure Homebrew installations also have a predictable installation of `ffmpeg` and `manim` that `git-sim` can depend on.

**Comment by initialcommit-io** [comment]
Gotcha, thanks for the details! I'll close this for now but feel free to let me know if I can help in any other way.  Also if git-sim does get accepted, let me know if you get a chance :D.
