### ISSUE TITLE
Webm output

### ISSUE THREAD

**Issue by TheKnarf** [initialcommit-com/git-sim#13]
It would be nice with support for outputting `.webm` videos.

**Comment by initialcommit-io** [comment]
@TheKnarf Thanks for the suggestion. Currently Manim only supports exporting to .mp4 or .gif.

Can you let me know your use case for .webm exports and why the currently exported .mp4 can't just be converted to .webm after it is generated?

**Comment by initialcommit-io** [comment]
Hi @TheKnarf,

Just following up to see if you can provide those details.

**Comment by abhijitnathwani** [comment]
I have seen webm widely used in webpages to embed videos. @TheKnarf put up a nice use case. 
@initialcommit-io we do have `ffmpeg` installed as part of manim dependencies. May be we can accept an argument to output as webm and internally convert the MP4 to webm using ffmpeg ?

**Comment by initialcommit-io** [comment]
@TheKnarf Sounds like a cool use case - ok we'll give it a try!

@abhijitnathwani Good suggestion - do you want to try your hand at implementing this with calls to ffmpeg?  I think a global option like `--video-format=webm` would work well.

**Comment by abhijitnathwani** [comment]
Sure @initialcommit-io ! I'll give it a try and let you know how it goes

**Comment by abhijitnathwani** [comment]
@initialcommit-io I have the bare bones working for the webm output. You can find the code in the branch [here](https://github.com/abhijitnathwani/git-sim/tree/add-support-for-webm-output).
One question for you, the mp4 to webm conversion takes a few seconds to run. While ffmpeg is running, the user doesn't see any messages so he/she is kinda lost at what is happening. How do we address this better? 

On another note, we need to add some logging so that we can also enable verbose mode to the dev can follow the flow.

**Comment by initialcommit-io** [comment]
@abhijitnathwani Looks good!  As for logging, it's a good point and we should switch to an actual logging facility instead of just print statements like you said, and I also do like the idea of the `--verbose` flag to enable detailed output.

For now, I think you can just add a print statement that says "Converting video output to .webm format..."  Then feel free to submit the PR for merging.

Then we can address logging in a new issue if you want to open an issue for that.  It would also be cool to do a separate issue for showing progress bars (not sure if we could get one for the Manim generation itself), but lets try and keep each of these functionalities as its own separate GitHub issue.
