### ISSUE TITLE
Feature request: support `git switch`

### ISSUE THREAD

**Issue by aunsbjerg** [initialcommit-com/git-sim#15]
The `switch` command is generally recommended over `checkout` for a few years now (as far as I know at least), so it would be nice if `git-sim` could also support `switch`.

**Comment by initialcommit-io** [comment]
@aunsbjerg Sure we can do that, just need some time since currently Git-Sim doesn't even support `git checkout` yet ':)

**Comment by Elleriyc** [comment]
Hello, this issue is still available ?

**Comment by initialcommit-io** [comment]
@Elleriyc We're working on this one!

**Comment by initialcommit-io** [comment]
@aunsbjerg @Elleriyc This is included in our latest release along with several other new git-sim subcommands for simulating git switch, checkout, clone, fetch, pull, and push!

To upgrade git-sim just run `pip install git-sim --upgrade`

I'll close this for now since the feature is implemented, but feel free to add any questions, comments, or if you run into any issues!
