### ISSUE TITLE
git submodule not support

### ISSUE THREAD

**Issue by gongheng** [initialcommit-com/git-sim#78]

**Comment by paketb0te** [comment]
Not sure if this is worth implementing, seeing that the history of a git repository and the history of its submodules are unrelate :thinking: 

Also, its trivial to run `git-sim` for a submodule separately by changing into its directory...

**Comment by initialcommit-io** [comment]
@paketb0te It's a fair point, but I think it's worth it to visually implement something for the various git submodule commands since they can be very confusing to many users.

We've also had multiple users request this feature.  It doesn't have to be complex, but at least a simple visualization of what each of the most common submodule options will do.
